String = "mi mama me mima"
contador= 0
print(String.center(40, "="))
contador=String.count("M")
print(f"\nLetra M se encontro {contador} veces en la cadena:{String}")
contador=String.count("m")
print(f"\nLetra m se encontro {contador} veces en la cadena:{String}")
contador=String.count("mama")
print(f"\nLetra mama se encontro {contador} veces en la cadena:{String}")
contador=String.count("me mima")
print(f"\nLetra M se encontro {contador} veces en la cadena:{String}")
contador=String.count("ma")
print(f"\nLetra M se encontro {contador} veces en la cadena:{String}")
contador=String.count("m", 13)
print(f"\nLetra M se encontro {contador} desde la pocicion 13 en la cadena:{String}")
contador=String.count("m", 100)
print(f"\nLetra M se encontro {contador} desde la pocicion 100 en la cadena:{String}")
contador=String.count("m", -3)
print(f"\nLetra M se encontro {contador} desde la pocicion - 3 en la cadena:{String}")
contador=String.count("m", 3, 7)
print(f"\nLetra M se encontro {contador} desde la pocicion 3 hasta la pocicion 7 en la cadena:{String}")
contador=String.count("m", 100, 100)
print(f"\nLetra M se encontro {contador} desde la pocicion 100 hasta la pocicion 100 en la cadena:{String}")
contador=String.count("m", -4, -1)
print(f"\nLetra M se encontro {contador} desde la pocicion -4 hasta la pocicion -1 en la cadena:{String}")